# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.30

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/raph/Projects/Cnake

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/raph/Projects/Cnake

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/raph/Projects/Cnake/CMakeFiles /home/raph/Projects/Cnake//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/raph/Projects/Cnake/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named cnake

# Build rule for target.
cnake: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cnake
.PHONY : cnake

# fast build rule for target.
cnake/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cnake.dir/build.make CMakeFiles/cnake.dir/build
.PHONY : cnake/fast

#=============================================================================
# Target rules for targets named cnakepp

# Build rule for target.
cnakepp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cnakepp
.PHONY : cnakepp

# fast build rule for target.
cnakepp/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cnakepp.dir/build.make CMakeFiles/cnakepp.dir/build
.PHONY : cnakepp/fast

cnake_src/colors.o: cnake_src/colors.c.o
.PHONY : cnake_src/colors.o

# target to build an object file
cnake_src/colors.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cnake.dir/build.make CMakeFiles/cnake.dir/cnake_src/colors.c.o
.PHONY : cnake_src/colors.c.o

cnake_src/colors.i: cnake_src/colors.c.i
.PHONY : cnake_src/colors.i

# target to preprocess a source file
cnake_src/colors.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cnake.dir/build.make CMakeFiles/cnake.dir/cnake_src/colors.c.i
.PHONY : cnake_src/colors.c.i

cnake_src/colors.s: cnake_src/colors.c.s
.PHONY : cnake_src/colors.s

# target to generate assembly for a file
cnake_src/colors.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cnake.dir/build.make CMakeFiles/cnake.dir/cnake_src/colors.c.s
.PHONY : cnake_src/colors.c.s

cnake_src/game.o: cnake_src/game.c.o
.PHONY : cnake_src/game.o

# target to build an object file
cnake_src/game.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cnake.dir/build.make CMakeFiles/cnake.dir/cnake_src/game.c.o
.PHONY : cnake_src/game.c.o

cnake_src/game.i: cnake_src/game.c.i
.PHONY : cnake_src/game.i

# target to preprocess a source file
cnake_src/game.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cnake.dir/build.make CMakeFiles/cnake.dir/cnake_src/game.c.i
.PHONY : cnake_src/game.c.i

cnake_src/game.s: cnake_src/game.c.s
.PHONY : cnake_src/game.s

# target to generate assembly for a file
cnake_src/game.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cnake.dir/build.make CMakeFiles/cnake.dir/cnake_src/game.c.s
.PHONY : cnake_src/game.c.s

cnake_src/leaderboard.o: cnake_src/leaderboard.c.o
.PHONY : cnake_src/leaderboard.o

# target to build an object file
cnake_src/leaderboard.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cnake.dir/build.make CMakeFiles/cnake.dir/cnake_src/leaderboard.c.o
.PHONY : cnake_src/leaderboard.c.o

cnake_src/leaderboard.i: cnake_src/leaderboard.c.i
.PHONY : cnake_src/leaderboard.i

# target to preprocess a source file
cnake_src/leaderboard.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cnake.dir/build.make CMakeFiles/cnake.dir/cnake_src/leaderboard.c.i
.PHONY : cnake_src/leaderboard.c.i

cnake_src/leaderboard.s: cnake_src/leaderboard.c.s
.PHONY : cnake_src/leaderboard.s

# target to generate assembly for a file
cnake_src/leaderboard.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cnake.dir/build.make CMakeFiles/cnake.dir/cnake_src/leaderboard.c.s
.PHONY : cnake_src/leaderboard.c.s

cnake_src/main.o: cnake_src/main.c.o
.PHONY : cnake_src/main.o

# target to build an object file
cnake_src/main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cnake.dir/build.make CMakeFiles/cnake.dir/cnake_src/main.c.o
.PHONY : cnake_src/main.c.o

cnake_src/main.i: cnake_src/main.c.i
.PHONY : cnake_src/main.i

# target to preprocess a source file
cnake_src/main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cnake.dir/build.make CMakeFiles/cnake.dir/cnake_src/main.c.i
.PHONY : cnake_src/main.c.i

cnake_src/main.s: cnake_src/main.c.s
.PHONY : cnake_src/main.s

# target to generate assembly for a file
cnake_src/main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cnake.dir/build.make CMakeFiles/cnake.dir/cnake_src/main.c.s
.PHONY : cnake_src/main.c.s

cnake_src/optionmenu.o: cnake_src/optionmenu.c.o
.PHONY : cnake_src/optionmenu.o

# target to build an object file
cnake_src/optionmenu.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cnake.dir/build.make CMakeFiles/cnake.dir/cnake_src/optionmenu.c.o
.PHONY : cnake_src/optionmenu.c.o

cnake_src/optionmenu.i: cnake_src/optionmenu.c.i
.PHONY : cnake_src/optionmenu.i

# target to preprocess a source file
cnake_src/optionmenu.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cnake.dir/build.make CMakeFiles/cnake.dir/cnake_src/optionmenu.c.i
.PHONY : cnake_src/optionmenu.c.i

cnake_src/optionmenu.s: cnake_src/optionmenu.c.s
.PHONY : cnake_src/optionmenu.s

# target to generate assembly for a file
cnake_src/optionmenu.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cnake.dir/build.make CMakeFiles/cnake.dir/cnake_src/optionmenu.c.s
.PHONY : cnake_src/optionmenu.c.s

cnake_src/startscreen.o: cnake_src/startscreen.c.o
.PHONY : cnake_src/startscreen.o

# target to build an object file
cnake_src/startscreen.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cnake.dir/build.make CMakeFiles/cnake.dir/cnake_src/startscreen.c.o
.PHONY : cnake_src/startscreen.c.o

cnake_src/startscreen.i: cnake_src/startscreen.c.i
.PHONY : cnake_src/startscreen.i

# target to preprocess a source file
cnake_src/startscreen.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cnake.dir/build.make CMakeFiles/cnake.dir/cnake_src/startscreen.c.i
.PHONY : cnake_src/startscreen.c.i

cnake_src/startscreen.s: cnake_src/startscreen.c.s
.PHONY : cnake_src/startscreen.s

# target to generate assembly for a file
cnake_src/startscreen.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cnake.dir/build.make CMakeFiles/cnake.dir/cnake_src/startscreen.c.s
.PHONY : cnake_src/startscreen.c.s

cnake_src/vector.o: cnake_src/vector.c.o
.PHONY : cnake_src/vector.o

# target to build an object file
cnake_src/vector.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cnake.dir/build.make CMakeFiles/cnake.dir/cnake_src/vector.c.o
.PHONY : cnake_src/vector.c.o

cnake_src/vector.i: cnake_src/vector.c.i
.PHONY : cnake_src/vector.i

# target to preprocess a source file
cnake_src/vector.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cnake.dir/build.make CMakeFiles/cnake.dir/cnake_src/vector.c.i
.PHONY : cnake_src/vector.c.i

cnake_src/vector.s: cnake_src/vector.c.s
.PHONY : cnake_src/vector.s

# target to generate assembly for a file
cnake_src/vector.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cnake.dir/build.make CMakeFiles/cnake.dir/cnake_src/vector.c.s
.PHONY : cnake_src/vector.c.s

cnakepp_src/food.o: cnakepp_src/food.cpp.o
.PHONY : cnakepp_src/food.o

# target to build an object file
cnakepp_src/food.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cnakepp.dir/build.make CMakeFiles/cnakepp.dir/cnakepp_src/food.cpp.o
.PHONY : cnakepp_src/food.cpp.o

cnakepp_src/food.i: cnakepp_src/food.cpp.i
.PHONY : cnakepp_src/food.i

# target to preprocess a source file
cnakepp_src/food.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cnakepp.dir/build.make CMakeFiles/cnakepp.dir/cnakepp_src/food.cpp.i
.PHONY : cnakepp_src/food.cpp.i

cnakepp_src/food.s: cnakepp_src/food.cpp.s
.PHONY : cnakepp_src/food.s

# target to generate assembly for a file
cnakepp_src/food.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cnakepp.dir/build.make CMakeFiles/cnakepp.dir/cnakepp_src/food.cpp.s
.PHONY : cnakepp_src/food.cpp.s

cnakepp_src/game_manager.o: cnakepp_src/game_manager.cpp.o
.PHONY : cnakepp_src/game_manager.o

# target to build an object file
cnakepp_src/game_manager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cnakepp.dir/build.make CMakeFiles/cnakepp.dir/cnakepp_src/game_manager.cpp.o
.PHONY : cnakepp_src/game_manager.cpp.o

cnakepp_src/game_manager.i: cnakepp_src/game_manager.cpp.i
.PHONY : cnakepp_src/game_manager.i

# target to preprocess a source file
cnakepp_src/game_manager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cnakepp.dir/build.make CMakeFiles/cnakepp.dir/cnakepp_src/game_manager.cpp.i
.PHONY : cnakepp_src/game_manager.cpp.i

cnakepp_src/game_manager.s: cnakepp_src/game_manager.cpp.s
.PHONY : cnakepp_src/game_manager.s

# target to generate assembly for a file
cnakepp_src/game_manager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cnakepp.dir/build.make CMakeFiles/cnakepp.dir/cnakepp_src/game_manager.cpp.s
.PHONY : cnakepp_src/game_manager.cpp.s

cnakepp_src/main.o: cnakepp_src/main.cpp.o
.PHONY : cnakepp_src/main.o

# target to build an object file
cnakepp_src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cnakepp.dir/build.make CMakeFiles/cnakepp.dir/cnakepp_src/main.cpp.o
.PHONY : cnakepp_src/main.cpp.o

cnakepp_src/main.i: cnakepp_src/main.cpp.i
.PHONY : cnakepp_src/main.i

# target to preprocess a source file
cnakepp_src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cnakepp.dir/build.make CMakeFiles/cnakepp.dir/cnakepp_src/main.cpp.i
.PHONY : cnakepp_src/main.cpp.i

cnakepp_src/main.s: cnakepp_src/main.cpp.s
.PHONY : cnakepp_src/main.s

# target to generate assembly for a file
cnakepp_src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cnakepp.dir/build.make CMakeFiles/cnakepp.dir/cnakepp_src/main.cpp.s
.PHONY : cnakepp_src/main.cpp.s

cnakepp_src/snake.o: cnakepp_src/snake.cpp.o
.PHONY : cnakepp_src/snake.o

# target to build an object file
cnakepp_src/snake.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cnakepp.dir/build.make CMakeFiles/cnakepp.dir/cnakepp_src/snake.cpp.o
.PHONY : cnakepp_src/snake.cpp.o

cnakepp_src/snake.i: cnakepp_src/snake.cpp.i
.PHONY : cnakepp_src/snake.i

# target to preprocess a source file
cnakepp_src/snake.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cnakepp.dir/build.make CMakeFiles/cnakepp.dir/cnakepp_src/snake.cpp.i
.PHONY : cnakepp_src/snake.cpp.i

cnakepp_src/snake.s: cnakepp_src/snake.cpp.s
.PHONY : cnakepp_src/snake.s

# target to generate assembly for a file
cnakepp_src/snake.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cnakepp.dir/build.make CMakeFiles/cnakepp.dir/cnakepp_src/snake.cpp.s
.PHONY : cnakepp_src/snake.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... cnake"
	@echo "... cnakepp"
	@echo "... cnake_src/colors.o"
	@echo "... cnake_src/colors.i"
	@echo "... cnake_src/colors.s"
	@echo "... cnake_src/game.o"
	@echo "... cnake_src/game.i"
	@echo "... cnake_src/game.s"
	@echo "... cnake_src/leaderboard.o"
	@echo "... cnake_src/leaderboard.i"
	@echo "... cnake_src/leaderboard.s"
	@echo "... cnake_src/main.o"
	@echo "... cnake_src/main.i"
	@echo "... cnake_src/main.s"
	@echo "... cnake_src/optionmenu.o"
	@echo "... cnake_src/optionmenu.i"
	@echo "... cnake_src/optionmenu.s"
	@echo "... cnake_src/startscreen.o"
	@echo "... cnake_src/startscreen.i"
	@echo "... cnake_src/startscreen.s"
	@echo "... cnake_src/vector.o"
	@echo "... cnake_src/vector.i"
	@echo "... cnake_src/vector.s"
	@echo "... cnakepp_src/food.o"
	@echo "... cnakepp_src/food.i"
	@echo "... cnakepp_src/food.s"
	@echo "... cnakepp_src/game_manager.o"
	@echo "... cnakepp_src/game_manager.i"
	@echo "... cnakepp_src/game_manager.s"
	@echo "... cnakepp_src/main.o"
	@echo "... cnakepp_src/main.i"
	@echo "... cnakepp_src/main.s"
	@echo "... cnakepp_src/snake.o"
	@echo "... cnakepp_src/snake.i"
	@echo "... cnakepp_src/snake.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

